trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    name: public_key
    inputs:
      secureFile: 'azure_ssh.pub'
  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
      commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(public_key.secureFilePath)'
      backendServiceArm: 'azure-service-connection'
      backendAzureRmResourceGroupName: 'azure-devops-terraform-backend-rg'
      backendAzureRmStorageAccountName: 'storageaccountruiwen123'
      backendAzureRmContainerName: 'storageaccountruiwen123container'
      backendAzureRmKey: 'test.tfstate'
      
  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
      commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(public_key.secureFilePath)'
      environmentServiceNameAzureRM: 'azure-service-connection'
