trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DownloadSecureFile@1
        name: public_key
        inputs:
          secureFile: 'azure_ssh.pub'
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
          commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(public_key.secureFilePath)'
          backendType: 'azurerm'
          backendServiceArm: 'azure-service-connection'
          ensureBackend: true
          backendAzureRmResourceGroupName: 'azure-devops-terraform-backend-rg'
          backendAzureRmResourceGroupLocation: 'eastasia'
          backendAzureRmStorageAccountName: 'storageaccountruiwen123'
          backendAzureRmContainerName: 'storageaccountruiwen123container'
          backendAzureRmKey: 'test.tfstate'
          allowTelemetryCollection: true
